/**
 * Created by sdaniels on 9/8/15.
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * https://projecteuler.net/problem=2
 */
(function() {
    "use strict";

    var evenFibonacci = {
        MAX: 4000000,
        evenTotal: 0,

        generate: function () {
            var num = 1;
            var sequence = [num];

            //console.log(num);
            while(num <= this.MAX) {
                //console.log(num);
                sequence.push(num);
                num = sequence[sequence.length - 1] + sequence[sequence.length - 2];

                if (num % 2 === 0) {
                    this.updateTotal(num);
                }
            }
        },

        updateTotal: function (amt) {
            this.evenTotal = this.evenTotal + amt;
        }
    }

    evenFibonacci.generate();
    console.log(evenFibonacci.evenTotal);

})();